# Customize these with your info 

title: "Canned Dragons" 
author: Robert Rackley
email: "robert@canneddragons.net"
description: "A weblog about faith, noise and tech."
github: frostedechoes
timezone: Europe/Amsterdam
url: https://canned-dragons.netlify.app/
language: en_US

# social images

favicon: /static/about-pictures/blue-dragon.png
social-media-image-url: /static/about-pictures/dragonmap.jpeg
twitter-card-image: canned-dragons/static/about-pictures/dragonmap.jpeg
iOS-icon: /static/about-pictures/blue-dragon.png

# leave these unless you are more familiar with jekyll settings

excerpt_separator: "<!--more-->"
paginate: 5
highlighter: rouge
markdown: kramdown
parse_block_html: false
show_drafts: false
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      blogpost: true
      layout: post
      og-type: article
      social-media-image: false
    
  -    
    scope:
      path: ""
      type: "pages"
    values:
      layout: page 
      social-media-image: false   

  -    
    scope:
      path: ""
      type: "no-index"
    values:
      layout: page
      no-index: true
      social-media-image: false

collections:
  pages:
    output: true
  no-index:
    output: true
  unlisted:
    output: true

plugins:
  - jekyll-feed

feed:
  posts_limit: 25
  categories:
    - essays
    - notes
    - now